### ISSUE TITLE
GitHub and Trello scripts should have consistent usage

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/ninja-points#4]
In order to support our process, I would like to see both of our reporting scripts follow a similar usage format. Here are the changes I'm proposing (some of these may already be done). Both scripts should:

1. Use the same default start date (March 1 of previous calendar year)
2. take an alternate start date as a parameter
3. Allow to target a specific user rather than running a full report
4. Use environment variables to load API credentials
5. Not require any changes to the script to run (externalize all config options)

**Comment by sabre1041** [comment]
@etsauer is this now complete?
